### ISSUE TITLE
API doesn't work in EE

### ISSUE THREAD

**Issue by romainds-tech** [teableio/teable#1148]
**Describe the bug**
I got a : 

{
    "message": "Internal Server Error",
    "status": 500,
    "code": "internal_server_error"
}

to every api call I try (It's the first time I try the API so I don't know if that worked one day)

**To Reproduce**
Create a new EE deploy

1. Create a token API
2. Create simple request with the query builder
3. copy cURL request created on terminal
4. send request
5. check there is something wrong

Exemple of cURL created : 
curl -X GET \
  "https://mydomain/api/table/tblXtxWwl2Xpyt5rNu0/record" \
  -H "Authorization: Bearer my_api_key_created_with_all_rights" \
  -H "Accept: application/json"

**Expected behavior**
Can use API

** Client**

- macos
- chrome
- Version 131.0.6778.109

**Platform**
docker-ee

**Additional context**
Here the error logs with modified sensitive data

```bash
{
  "level": 50,
  "time": 1733503267802,
  "pid": 7,
  "hostname": "9ec153fca208",
  "name": "teable",
  "req": {
    "id": "masked_request_id",
    "method": "GET",
    "url": "/api/table/masked_table_id/record",
    "query": {},
    "params": {
      "0": "api/table/masked_table_id/record"
    },
    "remoteAddress": "masked_remote_address",
    "remotePort": 48148
  },
  "trace_id": "masked_trace_id",
  "span_id": "masked_span_id",
  "trace_flags": "01",
  "context": "AuthGuard",
  "spanId": "masked_span_id",
  "traceId": "masked_trace_id",
  "msg": "Auth session cookie is not found in request cookies"
}

{
  "level": 50,
  "time": 1733503267806,
  "pid": 7,
  "hostname": "9ec153fca208",
  "name": "teable",
  "req": {
    "id": "masked_request_id",
    "method": "GET",
    "url": "/api/table/masked_table_id/record",
    "query": {},
    "params": {
      "0": "api/table/masked_table_id/record"
    },
    "remoteAddress": "masked_remote_address",
    "remotePort": 48148
  },
  "trace_id": "masked_trace_id",
  "span_id": "masked_span_id",
  "trace_flags": "01",
  "context": "GlobalExceptionFilter",
  "url": "/api/table/masked_table_id/record",
  "message": "Decryption failed",
  "spanId": "masked_span_id",
  "traceId": "masked_trace_id",
  "msg": "Error: Decryption failed\n    at Encryptor.decrypt (/app/enterprise/backend-ee/dist/index.js:1610:19)\n    at splitAccessToken (/app/enterprise/backend-ee/dist/index.js:1542:48)\n    at AccessTokenStrategy.authenticate (/app/enterprise/backend-ee/dist/index.js:54879:78)\n    at attempt (/app/node_modules/.pnpm/passport@0.7.0/node_modules/passport/lib/middleware/authenticate.js:378:16)\n    at strategy.fail (/app/node_modules/.pnpm/passport@0.7.0/node_modules/passport/lib/middleware/authenticate.js:314:9)\n    at SessionStrategy.authenticate (/app/enterprise/backend-ee/dist/index.js:55079:13)\n    at attempt (/app/node_modules/.pnpm/passport@0.7.0/node_modules/passport/lib/middleware/authenticate.js:378:16)\n    at authenticate (/app/node_modules/.pnpm/passport@0.7.0/node_modules/passport/lib/middleware/authenticate.js:379:7)\n    at /app/node_modules/.pnpm/@nestjs+passport@10.0.3_@nestjs+common@10.3.5_passport@0.7.0/node_modules/@nestjs/passport/dist/auth.guard.js:88:3\n    at new Promise (<anonymous>)"
}

{
  "level": 30,
  "time": 1733503267808,
  "pid": 7,
  "hostname": "9ec153fca208",
  "name": "teable",
  "req": {
    "id": "masked_request_id",
    "method": "GET",
    "url": "/api/table/masked_table_id/record",
    "query": {},
    "params": {
      "0": "api/table/masked_table_id/record"
    },
    "remoteAddress": "masked_remote_address",
    "remotePort": 48148
  },
  "trace_id": "masked_trace_id",
  "span_id": "masked_span_id",
  "trace_flags": "01",
  "res": {
    "statusCode": 500
  },
  "err": {
    "type": "Error",
    "message": "failed with status code 500",
    "stack": "Error: failed with status code 500\n    at onResFinished (/app/node_modules/.pnpm/pino-http@9.0.0/node_modules/pino-http/logger.js:114:39)\n    at ServerResponse.onResponseComplete (/app/node_modules/.pnpm/pino-http@9.0.0/node_modules/pino-http/logger.js:177:14)\n    at /app/node_modules/.pnpm/@opentelemetry+context-async-hooks@1.27.0_@opentelemetry+api@1.9.0/node_modules/@opentelemetry/context-async-hooks/build/src/AbstractAsyncHooksContextManager.js:50:55\n    at AsyncLocalStorage.run (node:async_hooks:335:14)\n    at AsyncLocalStorageContextManager.with (/app/node_modules/.pnpm/@opentelemetry+context-async-hooks@1.27.0_@opentelemetry+api@1.9.0/node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)\n    at ServerResponse.contextWrapper (/app/node_modules/.pnpm/@opentelemetry+context-async-hooks@1.27.0_@opentelemetry+api@1.9.0/node_modules/@opentelemetry/context-async-hooks/build/src/AbstractAsyncHooksContextManager.js:50:32)\n    at ServerResponse.emit (node:events:526:35)\n    at ServerResponse.emit (node:domain:488:12)\n    at onFinish (node:_http_outgoing:1005:10)\n    at callback (node:internal/streams/writable:608:21)"
  },
  "responseTime": 10,
  "spanId": "masked_span_id",
  "traceId": "masked_trace_id",
  "msg": "request errored"
}
```

**Comment by tea-artist** [comment]
Is there a selection of data range after selecting permissions, such as a certain space or a certain base?
