### ISSUE TITLE
Attachment missing when switching between gallery and grid view

### ISSUE THREAD

**Issue by Tonghua-Li** [teableio/teable#1155]
**Describe the bug**
Attachments are missing after switching between gallery and grid view multiple times

**To Reproduce**

1. Create a column with attachment type
2. click the attachment cell and upload an image
3. Create a grid view
4. switch between grid view and gallery view
5. images are missing

**Expected behavior**
images should not missing

**Screenshots**
![image](https://github.com/user-attachments/assets/8b9ef90f-ef11-41ac-b224-f7b0ddf2de63)

![image](https://github.com/user-attachments/assets/a8f5f768-1537-472a-8971-f9b35ccc1c5e)

** Client (please complete the following information):**

- OS: Linux
- Browser: vivaldi
- Version 1.5.2-alpha+build.699

**Platform (Please tell us which deployment version you are using)**
docker-standalone

**Additional context**

**Comment by tea-artist** [comment]
We may need error logs of the browser console.

**Comment by Tonghua-Li** [comment]
I don't have it right now, you can try the steps see if it is reproducible.

**Comment by Tonghua-Li** [comment]
@tea-artist 
```
7678-ca3345bd07238e26.js:42 tbl_bseUHNPqFEjEYkzXLi9:ready: Object null
7678-ca3345bd07238e26.js:42 extra ready -> undefined
7678-ca3345bd07238e26.js:42 tbl_bseUHNPqFEjEYkzXLi9:insert: Array(1) 0
7678-ca3345bd07238e26.js:42 tbl_bseUHNPqFEjEYkzXLi9:changed: Array(1)
main-04db6bf4f8c5e575.js:1 Error: Abort fetching component for route: "/base/[baseId]/[tableId]/[viewId]"
    at main-04db6bf4f8c5e575.js:1:63852
    at V.getRouteInfo (main-04db6bf4f8c5e575.js:1:73014)
    at async V.change (main-04db6bf4f8c5e575.js:1:68010)
handleRouteInfoError @ main-04db6bf4f8c5e575.js:1
7678-ca3345bd07238e26.js:42 viw_tblcdG5TTgUqu8WP7Fp:ready: Object null
7678-ca3345bd07238e26.js:42 extra ready -> undefined
7678-ca3345bd07238e26.js:42 fld_tblcdG5TTgUqu8WP7Fp:ready: Object null
7678-ca3345bd07238e26.js:42 extra ready -> undefined
7678-ca3345bd07238e26.js:42 rec_tblcdG5TTgUqu8WP7Fp:ready: Object null
7678-ca3345bd07238e26.js:42 extra ready -> Object
7678-ca3345bd07238e26.js:42 viw_tblcdG5TTgUqu8WP7Fp on op: Array(1) p
7678-ca3345bd07238e26.js:42 fld_tblcdG5TTgUqu8WP7Fp:insert: Array(1) 3
7678-ca3345bd07238e26.js:42 fld_tblcdG5TTgUqu8WP7Fp:changed: Array(4)
7678-ca3345bd07238e26.js:42 rec_tblcdG5TTgUqu8WP7Fp on op: Array(1) p
1955-87a48a82a4c4272b.js:1 updateRowCountForTable
7678-ca3345bd07238e26.js:42 viw_tblcdG5TTgUqu8WP7Fp:insert: Array(1) 1
7678-ca3345bd07238e26.js:42 viw_tblcdG5TTgUqu8WP7Fp:changed: Array(2)
7678-ca3345bd07238e26.js:42 fld_tblcdG5TTgUqu8WP7Fp:ready: Object null
7678-ca3345bd07238e26.js:42 extra ready -> undefined
7678-ca3345bd07238e26.js:42 rec_tblcdG5TTgUqu8WP7Fp:ready: Object null
7678-ca3345bd07238e26.js:42 extra ready -> Object
7678-ca3345bd07238e26.js:42 fld_tblcdG5TTgUqu8WP7Fp:ready: Object null
7678-ca3345bd07238e26.js:42 extra ready -> undefined
7678-ca3345bd07238e26.js:42 rec_tblcdG5TTgUqu8WP7Fp:ready: Object null
7678-ca3345bd07238e26.js:42 extra ready -> Object
7678-ca3345bd07238e26.js:42 fld_tblcdG5TTgUqu8WP7Fp:ready: Object null
7678-ca3345bd07238e26.js:42 extra ready -> undefined
7678-ca3345bd07238e26.js:42 rec_tblcdG5TTgUqu8WP7Fp:ready: Object null
7678-ca3345bd07238e26.js:42 extra ready -> Object
7678-ca3345bd07238e26.js:42 fld_tblcdG5TTgUqu8WP7Fp:ready: Object null
7678-ca3345bd07238e26.js:42 extra ready -> undefined
7678-ca3345bd07238e26.js:42 rec_tblcdG5TTgUqu8WP7Fp:ready: Object null
7678-ca3345bd07238e26.js:42 extra ready -> Object
Ajg8V8ILywAS_sm:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE.NotSameOrigin
7678-ca3345bd07238e26.js:42 fld_tblcdG5TTgUqu8WP7Fp:ready: Object null
7678-ca3345bd07238e26.js:42 extra ready -> undefined
7678-ca3345bd07238e26.js:42 rec_tblcdG5TTgUqu8WP7Fp:ready: Object null
7678-ca3345bd07238e26.js:42 extra ready -> Object
Ajg8V8ILywAS_lg:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE.NotSameOrigin
7678-ca3345bd07238e26.js:42 fld_tblcdG5TTgUqu8WP7Fp:ready: Object null
7678-ca3345bd07238e26.js:42 extra ready -> undefined
7678-ca3345bd07238e26.js:42 rec_tblcdG5TTgUqu8WP7Fp:ready: Object null
7678-ca3345bd07238e26.js:42 extra ready -> Object
Ajg8V8ILywAS_sm:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE.NotSameOrigin
```

**Comment by Tonghua-Li** [comment]
@tea-artist looks like related to localhost, if using 127.0.0.1:3000 then it works fine
```
ERR_BLOCKED_BY_RESPONSE.NotSameOrigin
```
