### ISSUE TITLE
latest docker image error

### ISSUE THREAD

**Issue by armgong** [teableio/teable#1185]
**Describe the bug**
use docker compose to selfhost teable, but fail to start 

**To Reproduce**
use the docker compose file in github,  when docker compose up it first pull latest teable image ,then  show 
~~~
teable-1             | /app/packages/openapi/dist/openapi-snippet/openapi-to-har.js:363
teable-1             |     if (openApi.paths[path][method].servers)
teable-1             |                            ^
teable-1             |
teable-1             | TypeError: Cannot read properties of undefined (reading 'post')
teable-1             |     at getBaseUrl (/app/packages/openapi/dist/openapi-snippet/openapi-to-har.js:363:28)
teable-1             |     at Object.createHar [as getEndpoint] (/app/packages/openapi/dist/openapi-snippet/openapi-to-har.js:39:21)
teable-1             |     at Object.getEndpointSnippets (/app/packages/openapi/dist/openapi-snippet/index.js:29:31)
teable-1             |     at generateCodeSamples (/app/packages/openapi/dist/generate.schema.js:35:53)
teable-1             |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
teable-1             |     at async getOpenApiDocumentation (/app/packages/openapi/dist/generate.schema.js:68:9)
teable-1             |     at async setUpAppMiddleware (/app/apps/nestjs-backend/dist/index.js:44:38)
teable-1             |     at async bootstrap (/app/apps/nestjs-backend/dist/index.js:74:5)
teable-1             |     at async /app/apps/nestjs-backend/dist/index.js:45351:15
teable-1             |
teable-1             | Node.js v20.9.0

~~~

**Comment by rootforbid** [comment]
I have the same error. Everything was fine prior to this last docker image.

**Comment by mykolarudenko** [comment]
Same here

**Comment by tea-artist** [comment]
Fixed in the latest version
