### ISSUE TITLE
collaborator.resource_id does not exist in the current database

### ISSUE THREAD

**Issue by MyWay** [teableio/teable#866]
Hello, I'm getting the following as soon as I open teable's homepage:

```
{"level":50,"time":1724866112027,"pid":1,"hostname":"72081cf545ba","name":"teable","req":{"id":"a45c2e147b094a8c7f7f4140472fbe86","method":"GET","url":"/api/space","query":{},"params":{"0":"api/space"},"remoteAddress":"::ffff:127.0.0.1","remotePort":33520},"context":"GlobalExceptionFilter","url":"/api/space","message":"\nInvalid `prisma.collaborator.findMany()` invocation:\n\n\nThe column `collaborator.resource_id` does not exist in the current database.","spanId":"acf03d6c02fcdafb","traceId":"a45c2e147b094a8c7f7f4140472fbe86","msg":"PrismaClientKnownRequestError: \nInvalid `prisma.collaborator.findMany()` invocation:\n\n\nThe column `collaborator.resource_id` does not exist in the current database.\n    at In.handleRequestError (/app/node_modules/.pnpm/@prisma+client@5.11.0_prisma@5.11.0/node_modules/@prisma/client/runtime/library.js:122:6854)\n    at In.handleAndLogRequestError (/app/node_modules/.pnpm/@prisma+client@5.11.0_prisma@5.11.0/node_modules/@prisma/client/runtime/library.js:122:6188)\n    at In.request (/app/node_modules/.pnpm/@prisma+client@5.11.0_prisma@5.11.0/node_modules/@prisma/client/runtime/library.js:122:5896)\n    at async l (/app/node_modules/.pnpm/@prisma+client@5.11.0_prisma@5.11.0/node_modules/@prisma/client/runtime/library.js:127:10871)\n    at async SpaceService.getSpaceList (/app/apps/nestjs-backend/dist/index.js:33471:39)\n    at async SpaceController.getSpaceList (/app/apps/nestjs-backend/dist/index.js:33209:16)"}
```

Logs of db-migrate container:
```
DB Migrate Version: 1.3.1-alpha+build.480
wait-for  teable_db:5432 【postgresql】deploying.
database driver:【postgresql】, ready to start migration.
database driver:【postgresql】, migration success.
```

**Comment by boris-w** [comment]
Hi @MyWay , you can try updating the latest teable  images

**Comment by MyWay** [comment]
Thanks, solved.
